services:
  amministratore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myamministratore
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - mysagra_default

networks:
  mysagra_default:
    external: true
